"""empty message

Revision ID: 7a82ceaf8339
Revises: 2d087c3de74f
Create Date: 2021-02-09 14:01:34.196250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a82ceaf8339'
down_revision = '2d087c3de74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_facebook_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_image_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_website_link_key', 'Artist', type_='unique')
    op.drop_column('Artist', 'facebook_link')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_description')
    op.drop_constraint('Venue_facebook_link_key', 'Venue', type_='unique')
    op.drop_constraint('Venue_image_link_key', 'Venue', type_='unique')
    op.drop_constraint('Venue_website_link_key', 'Venue', type_='unique')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('Venue_website_link_key', 'Venue', ['website_link'])
    op.create_unique_constraint('Venue_image_link_key', 'Venue', ['image_link'])
    op.create_unique_constraint('Venue_facebook_link_key', 'Venue', ['facebook_link'])
    op.add_column('Artist', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('Artist_website_link_key', 'Artist', ['website_link'])
    op.create_unique_constraint('Artist_image_link_key', 'Artist', ['image_link'])
    op.create_unique_constraint('Artist_facebook_link_key', 'Artist', ['facebook_link'])
    # ### end Alembic commands ###
