"""empty message

Revision ID: dff062315fc9
Revises: 7a82ceaf8339
Create Date: 2021-02-09 14:03:13.258934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff062315fc9'
down_revision = '7a82ceaf8339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Artist', ['image_link'])
    op.create_unique_constraint(None, 'Artist', ['facebook_link'])
    op.create_unique_constraint(None, 'Artist', ['website_link'])
    op.add_column('Venue', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Venue', ['website_link'])
    op.create_unique_constraint(None, 'Venue', ['image_link'])
    op.create_unique_constraint(None, 'Venue', ['facebook_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'facebook_link')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'image_link')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
